language: ruby
rvm:
  - "2.3.0"
  - "2.2.4"
  - "2.1.8"
  - "2.0.0"
before_install:
  - cd ext/symbol_lookup && ruby extconf.rb && make && cp symbol_lookup.so ../../lib/ && cd ../..
script: "bundle exec rake test"
